export const metadata = {
  title: 'ChessnKaffe Log-in',
  description: 'Generated by Next.js',
}

export default function LoginLayout({ children }) {
  return (
    <>
      {children}
    </>
  )
}
