export const metadata = {
  title: 'ChessnKaffe Sign-up',
  description: 'Generated by Next.js',
}

export default function SignupLayout({ children }) {
  return (
    <>
      {children}
    </>
  )
}
